hydra:
  job:
    name: "demo"
  run:
    dir: "./experiments/${hydra.job.name}"

camera:
  id: 0
  width: 1920
  height: 1080
  roi:
    width: 640
    height: 790
  fps: 30
  num_frames: 5
  start_delay_seconds: 3

save:
  dir: "output_images"

processing:
  ground_truth_label: -1
  gamma: 0.375
  template_matching:
    rotations: [-2.5, 0.0, 2.5]
    scales: [0.75, 1.0]
    labels_file: "./templates/binary_images/labels.csv"
    images_dir: "./templates/binary_images"
