[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "a2"
version = "0.1.0"
requires-python = ">=3.8"
authors = [
  {name = "Alex Lavaee", email = "alavaee@bu.edu"}
]